server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://kbhmiyzrtpzlku:0b372e78ef5f3b8500a355ffc9e665fee56b0a745a23894ac7103f11b263ce15@ec2-50-16-108-41.compute-1.amazonaws.com:5432/d15t2b6r8sb0ql
    username: kbhmiyzrtpzlku
    password: 0b372e78ef5f3b8500a355ffc9e665fee56b0a745a23894ac7103f11b263ce15
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0